periban/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from landing import views as landing_views
from menus import views as menu_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tarjeta_p/<str:user_id>/', landing_views.presentation_card_01, name='pc_01'),
    path('links', landing_views.links, name='links'),
    path('', landing_views.home, name='home'),
    path('menu/', menu_views.menus, name="menus"),
    path('menu/<str:menu_name>/', menu_views.menu, name="menu"),
    path('menu/platillo/<str:name>/', menu_views.platillos, name="platillos"),
    path('servicio_domicilio/', landing_views.shipment, name="shipment"),
    path('cobertura/', landing_views.coverage, name="coverage"),
    path('sucursales/', landing_views.branches, name="branches"),
    path('eventos/', landing_views.events, name="events"),
    path('empleo/', landing_views.employees, name="employees"),
    path('medios/', landing_views.medios, name="medios"),
    path('facturacion/', landing_views.invoices, name="invoices"),
    path('aviso_privacidad/', landing_views.privacy_notice, name="privacy"),
    path('staff/', landing_views.login_view, name="login"),
    path('staff/logout', landing_views.logout_view, name="logout"),
    path('staff/formularios/', landing_views.forms_list, name="form_list"),
    path('staff/formularios/<str:form>', landing_views.form_view, name="form"),
    path('staff/formularios/respuestas/<str:form>', landing_views.form_answers, name="form_answers")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from datetime import date


class Profile(models.Model):
    """Profile Model"""

    OPERATOR = "Optor"
    ADMIN = "Admin"
    ROLES = [
        (ADMIN, "Administrador"),
        (OPERATOR, "Operador"),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=5, choices=ROLES, default=OPERATOR)


class Form_type(models.Model):
    """Questions Forms Model"""

    form_id = models.AutoField(primary_key=True)
    form_name = models.CharField(max_length=100, default="")
    is_active = models.BooleanField(default=True)
    total_points_promedy = models.IntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return self.form_name


class Question_form(models.Model):
    """Questions Forms Model"""

    question_id = models.AutoField(primary_key=True)
    question_description = models.CharField(max_length=700, default="")
    form_type = models.ForeignKey(Form_type, on_delete=models.CASCADE)
    is_options = models.BooleanField(default=False)
    is_check = models.BooleanField(default=False)
    is_time = models.BooleanField(default=False)
    is_picture = models.BooleanField(default=False)
    value_points = models.IntegerField(default=0, blank=False, null=False)
    options = models.TextField(blank=True, null=True)
    required = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)
    created = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_description

    class Meta(object):
        ordering = ["my_order"]


class answer_form(models.Model):
    form_id = models.IntegerField()
    form_type = models.ForeignKey(Form_type, on_delete=models.CASCADE, default="1")
    question_id = models.ForeignKey(Question_form, on_delete=models.CASCADE)
    answer = models.TextField(default="")
    answer_by = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    created = models.DateField(default=date.today)

    def __str__(self):
        return self.answer


class image_evidence(models.Model):
    id = models.AutoField(primary_key=True)
    form_id = models.IntegerField(default=1)
    image_evidence = models.ImageField(upload_to="landing/images/evidence", null=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-id",)


class promedy_form(models.Model):
    form_id = models.IntegerField()
    promedy_form = models.PositiveIntegerField(default=0, blank=False, null=False)
    created = models.DateField(default=date.today)

    def __str__(self):
        return self.promedy_form


class ticket_image_evidence(models.Model):
    id = models.AutoField(primary_key=True)
    client_name = models.CharField(max_length=300, default="", blank=True)
    ticket_image = models.ImageField(upload_to="landing/images/ticket_evidence", null=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-id",)

landing/forms.py
from django import forms
from landing.models import image_evidence, ticket_image_evidence


# Create your forms here.
class ImageForm(forms.ModelForm):
    class Meta:
        model = image_evidence
        fields = (
            "form_id",
            "image_evidence",
        )
        widgets = {"form_id": forms.HiddenInput()}

    def save(self, form_id=None):
        image_evidence = super(ImageForm, self).save(commit=False)
        if form_id:
            image_evidence.form_id = form_id
        image_evidence.save()
        return image_evidence


class ImageTicketForm(forms.ModelForm):
    class Meta:
        model = ticket_image_evidence
        fields = (
            "client_name",
            "ticket_image",
        )

    def save(self, client_name=None):
        ticket_image = super(ImageTicketForm, self).save(commit=False)
        if client_name:
            ticket_image.client_name = client_name
        ticket_image.save()
        return ticket_image

landing/views.py
"""Landing views"""
import pwd
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.mail import BadHeaderError, send_mail
from django.conf import settings
from typing import List, cast
from django.db.models import Count

from landing.forms import ImageForm, ImageTicketForm
from landing.models import Form_type, Question_form, answer_form, image_evidence, promedy_form

def home(request):
    return render(request, 'landing/home.html')

def login_view(request):
    if request.method == 'POST':
        user_name = request.POST.get('userName')
        pswd = request.POST.get('userPassword')
        user = authenticate(request, username=user_name,password=pswd)
        if user:
            login(request, user)
            return redirect('form_list')
        else:
           return render(request, 'landing/login.html', {'error': True}) 
    return render(request, 'landing/login.html')

def logout_view(request):
    """Logout user"""
    logout(request)
    return redirect('home')

def shipment(request):
    return render(request, 'landing/shipment.html')

def branches(request):
    return render(request, 'landing/branches.html')

def coverage(request):
    branch = request.GET.get('sucursal')
    if branch == 'ajusco':
        name = 'AJUSCO'
        address = 'Halacho esq. KinchilH. de Padierna,Tlalpan, CDMX'
        tel = '55 8791 3477'
        email = 'ajusco@elperiban.com'
        tel_link = '525587913477'
    if branch == 'aztecas':
        name = 'AZTECAS'
        address = 'Av. Aztecas 762, Ajusco Coyoacán, cdmx'
        tel = '55 1517 0679'
        email = 'aztecas@elperiban.com'
        tel_link = '525536523218'
    if branch == 'marina':
        name = 'MARINA'
        address = 'Marina Nac. 240, Anáhuac, Miguel Hidalgo, cdmx'
        tel = '55 6394 2221'
        email = 'marina@elperiban.com'
        tel_link = '525536523714'
    if branch == 'coapa':
        name = 'COAPA'
        address = 'Av. Prolongación División del Norte 4496 Prado Coapa, Tlalpan, CDMX'
        tel = '55 7259 0035'
        email = 'coapa@elperiban.com'
        tel_link = '525535569825'
    if branch == 'cafetales':
        name = 'CAFETALES'
        address = 'V. de la Armada 1405 Col. Residencial Cafetales del Coyoacán, CDMX'
        tel = '55 3559 4524'
        email = 'cafetales@elperiban.com'
        tel_link = '525535594524'
    if branch == 'ayuntamiento':
        name = 'AYUNTAMIENTO'
        address = 'Ayuntamiento 87 Local D, Barrio la Lonja, Tlalpan, CDMX'
        tel = '55 3652 3050'
        email = 'ayuntamiento@elperiban.com'
        tel_link = '525536523050'
    if branch == 'revolucion':
        name = 'REVOLUCIÓN'
        address = 'Av. revolución 1351-Local C, Campestre, Álvaro Obregón, CDMX'
        tel = '55 4957 7347'
        email = 'revolucion@elperiban.com'
        tel_link = '525549577347'
    if branch == 'universidad':
        name = 'UNIVERSIDAD'
        address = 'Av. Universidad 789, Del Valle, CDMX'
        tel = '55 5941 5084'
        email = 'universidad@elperiban.com'
        tel_link = '525559415084'
    return render(
        request,
        'landing/coverage.html',
        {
            "name": name,
            "address": address,
            "phone": tel,
            "email": email,
            "phone_link": tel_link
        }
    )

def events(request):
    if request.method == 'POST':
        client_name = request.POST.get('clientname')
        phone = request.POST.get('phone')
        date_event = request.POST.get('dateevent')
        num_persons = request.POST.get('numberpersons')
        email = request.POST.get('email')
        address = request.POST.get('address')
        subject = 'Cotización evento'
        message = f"""
            Cotización de evento para:
            nombre: {client_name}
            teléfono: {phone}
            correo: {email}
            fecha de evento: {date_event}
            numero de personas: {num_persons}
            dirección: {address}
        """
        email_from = settings.EMAIL_HOST_USER
        send_mail(subject, message, email_from, ['eventos@elperiban.com'], fail_silently=False)
        # except BadHeaderError:
        #     print('Invalid header found.')
    return render(request, 'landing/events.html')

def employees(request):
    if request.method == 'POST':
        name = request.POST.get('nameEmployee')
        last_name = request.POST.get('lastNameEmployee')
        phone = request.POST.get('phoneEmployee')
        interests = request.POST.get('vacancy')
        subject = 'Formulario de empleo'
        message = f"""
            Una persona lleno el formulario de bolsa de trabajo:
            nombre: {name} {last_name}
            teléfono: {phone}
            intereses: {interests}
        """
        email_from = settings.EMAIL_HOST_USER
        send_mail(subject, message, email_from, ['rh@elperiban.com'], fail_silently=False)
    return render(request, 'landing/employee.html')

def medios(request):
    return render(request, 'landing/medios.html')

@login_required
def forms_list(request):
    forms = Form_type.objects.all()
    forms_answer = answer_form.objects.values('form_id', 'form_type__form_id', 'form_type__form_name', 'created').annotate(dcount=Count('form_id'))
    # import pdb; pdb.set_trace()
    return render(request, 'landing/forms_list.html', {
        'forms': forms,
        'forms_answers': forms_answer
    })

@login_required
def form_view(request, form):
    if request.method == 'POST':
        answer_row = answer_form.objects.all().last()
        form_type = Form_type.objects.get(form_id=form)
        last_form = answer_row.form_id + 1 if answer_row else 1
        form_image = ImageForm(request.POST, request.FILES)
        checks = {}
        total_promedy = 0
        ####variables for email###
        body_email = ''
        email_destination = ''
        for i, qst_answer in request.POST.items():
            if i != 'csrfmiddlewaretoken' and i != 'imageEvidence' and i != 'form_id': 
                if len(i) > 1:
                    name_option=i.split("-")
                    checks[name_option[0]] = f'{checks[name_option[0]]};{qst_answer}' if checks.get(name_option[0]) else qst_answer
                else:
                    question = Question_form.objects.get(question_id=i)
                    if question.value_points > 0 and cast(str, qst_answer.lower()) == 'si':
                        total_promedy += question.value_points
                    answer = answer_form(
                        form_id=last_form,
                        form_type=form_type,
                        question_id=question,
                        answer=qst_answer,
                        answer_by=request.user
                    )
                    answer.save()
                    
                    #Data for email
                    if question.question_description == 'Sucursales':
                        email_destination = f"{answer.answer}@elperiban.com"
                    body_email = body_email + f"""
                        - {question.question_description}: {answer.answer}
                    """
        print(f'****total promedy: {total_promedy}')
        if len(checks) > 0:
            for i, check in checks.items():
                question = Question_form.objects.get(question_id=i)
                answer = answer_form(
                    form_id=last_form,
                    form_type=form_type,
                    question_id=question,
                    answer=check,
                    answer_by=request.user
                )
                answer.save()
                body_email = body_email + f"""
                    - {question.question_description}: {answer.answer}
                """
        if total_promedy > 0:
            promedy = promedy_form(
                form_id=last_form,
                promedy_form= total_promedy
            )
            promedy.save()
        form_image.save(last_form)
        """Send email with answers to branch"""
        subject = 'Respuestas formulario'
        email_from = settings.EMAIL_HOST_USER
        # send_mail(subject, body_email, email_from, [email_destination], fail_silently=False)
        return redirect('form_list')

    form_questions = Question_form.objects.filter(form_type__form_id=form)
    questions = []
    form_image = ImageForm()
    for qst in form_questions:
        options_list = qst.options.split(';') if qst.options else []
        questions.append({
            'id': qst.question_id,
            'label': qst.question_description,
            'is_options': qst.is_options,
            'is_check': qst.is_check,
            'options': {
                i : options_list[i] for i in range(len(options_list))
            }
        })
    return render(request, 'landing/forms_list.html', {
        'questions': questions,
        'form': form_questions[0].form_type,
        'image_form': form_image
    })

def form_answers(request, form):
    answers = answer_form.objects.filter(form_id=form)
    evidence = image_evidence.objects.get(form_id=form)
    promedy = promedy_form.objects.get(form_id=form)
    return render(request, 'landing/forms_list.html', {
        'answers': answers,
        'evidence': evidence,
        'date': answers[0].created,
        'form_type': answers[0].form_type.form_name,
        'applied': answers[0].answer_by,
        'promedy': promedy
    })    

def invoices(request):
    if request.method == 'POST':
        ticket_image = ImageTicketForm(request.POST, request.FILES)
        if not ticket_image.is_valid():
            print(f"***errors: {ticket_image.errors}")
        name = request.POST.get('nameInvoice')
        branch = request.POST.get('branchInvoice')
        rfc = request.POST.get('rfcInvoice')
        ticket_num = request.POST.get('ticketNum')

templates/landing/branches.html
{% extends "base.html" %}
{% load static %}
{% block container %}
    <div class="container-fluid principal-container p-0 shipment-branches d-flex flex-column align-items-center">
        <div class="container-title-branches">
            <img class="arm-pig" src="{% static 'img/arm_pig.png' %}" alt="">
            <div class="title-branches">
                <p class="disp-font yellow">Realiza tu pedido</p>
            </div>
        </div>
        <div class="container-addresses gobold">
            <div>
                <p class="type-branch">Restaurantes</p>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">AJUSCO</p>
                        <p>Halacho esq. KinchilH. de Padierna,Tlalpan, CDMX</p>
                        <p>ajusco@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/5587913477" target="_blank" class="brown2 mb-0">55 8791 3477</a>
                        </div>
                        <a href="tel:5556315062" class="brown2 mb-0 mt-1">Suc: 55 5631 5062</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">AZTECAS</p>
                        <p>Av. Aztecas 762, Ajusco Coyoacán, cdmx</p>
                        <p>aztecas@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525536523218" target="_blank" class="brown2 mb-0">55 3652 3218</a>
                        </div>
                        <a href="tel:5515170679" class="brown2 mb-0 mt-1">Suc: 55 1517 0679</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">MARINA</p>
                        <p>Marina Nac. 240, Anáhuac, Miguel Hidalgo, cdmx</p>
                        <p>marina@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525536523714" target="_blank" class="brown2 mb-0">55 3652 3714</a>
                        </div>
                        <a href="tel:55 6394 2221" class="brown2 mb-0 mt-1">Suc: 55 6394 2221</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">REVOLUCIÓN</p>
                        <p>Av. revolución 1351-Local C, Campestre, Álvaro Obregón, CDMX</p>
                        <p>revolucion@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525549577347" target="_blank" class="brown2 mb-0">55 4957 7347</a>
                        </div>
                        <a href="tel:5571635313" class="brown2 mb-0 mt-1">Suc: 55 7163 5313</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">UNIVERSIDAD</p>
                        <p>Av. Universidad 789, Del Valle, CDMX</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525620070032" target="_blank" class="brown2 mb-0">56 2007 0032</a>
                        </div>
                        <a href="tel:5559415084" class="brown2 mb-0 mt-1">Suc: 55 5941 5084</a>
                    </div>
                </div>
            </div>
            <div>
                <p class="type-branch mt-4">TAQUERÍAS</p>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">COAPA</p>
                        <p>
                            Av. Prolongación División del Norte 4496 
                            Prado Coapa, Tlalpan, CDMX</p>
                        <p>coapa@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525535569825" target="_blank" class="brown2 mb-0">55 3556 9825</a>
                        </div>
                        <a href="tel:5572590035" class="brown2 mb-0 mt-1">Suc: 55 7259 0035</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">Cafetales</p>
                        <p>V. de la Armada 1405 Col. Residencial Cafetales
                            del Coyoacán, CDMX</p>
                        <p>cafetales@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525535594524" target="_blank" class="brown2 mb-0">55 3559 4524</a>
                        </div>
                        <a href="tel:5526520576" class="brown2 mb-0 mt-1">Suc: 55 2652 0576</a>
                    </div>
                </div>
                <div class="branch d-flex justify-content-between">
                    <div class="branch-address">
                        <p class="brown2">Ayuntamiento</p>
                        <p>Ayuntamiento 87 Local D, Barrio la Lonja, Tlalpan, CDMX</p>
                        <p>ayuntamiento@elperiban.com</p>
                    </div>
                    <div class="wa-tel">
                        <div>
                            <img src="{% static 'img/whats_logo.png' %}" alt="">
                            <a href="https://wa.me/525536523050" target="_blank" class="brown2 mb-0">55 3652 3050</a>
                        </div>
                        <a href="tel:5571553607" class="brown2 mb-0 mt-1">Suc: 55 7155 3607</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/landing/coverage.html
{% extends "base.html" %}
{% load static %}
{% block container %}
    <div class="container-fluid principal-container p-0 shipment-coverage d-flex flex-column align-items-center">
        <img class="moto-pig" src="{% static 'img/moto-pig.png' %}" alt="">
        <div class="container-title-branches">
            <div class="title-coverage">
                <p class="disp-font yellow mb-0">Realiza tu pedido</p>
                <p class="goboldItalic subtitle-coverage">TIENES COBERTURA EN ESTAS SUCURSALES</p>
            </div>
        </div>
        <div class="container-addresses-coverage gobold">
            <div class="branch-coverage d-flex flex-column align-items-center">
                <p class="brown2 mb-0">{{name}}</p>
                <p>{{address}}</p>
                <p>{{email}}</p>
                <div class="wa-tel coverage">
                    <img src="{% static 'img/whats_logo.png' %}" alt="">
                    <a href="https://wa.me/{{phone_link}}" target="_blank" class="brown2 mb-0">{{phone}}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/landing/invoices.html
{% extends "base.html" %}
{% load static %}
{% block container %}
    <div class="container-fluid principal-container p-0 d-flex justify-content-center align-items-start">
            <div class="facturacion-container">
                <div class="title-form-facturacion">
                    <h1 class="gobold yellow">Aclaraciones de facturación</h1>
                </div>
                <div class="gobold">
                    <p class="subtitle-invoices">¿No te llega tu factura? Escríbenos</p> 
                </div>
                <div class="form-employees">
                    <form method="post" action="{% url 'invoices' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-container">
                                <label for="nameInputInvoice" class="form-label">Nombre Completo</label>
                                <input type="text" name="nameInvoice" class="form-control" id="nameInputInvoice" aria-describedby="emailHelp">    
                            </div>
                            <!-- <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Sucursal</label>
                                <input type="text" name="branchInvoice" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp">    
                            </div> -->
                            <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Sucursal</label>
                                <!-- <input type="text" name="rfcInvoice" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp">     -->
                                <select class="form-select" name="branchInvoice" aria-label="Sucursal">
                                    <option value="ajusco">Ajusco</option>
                                    <option value="aztecas">Aztecas</option>
                                    <option value="marina">Marina</option>
                                    <option value="roma">Roma</option>
                                    <option value="coapa">Coapa</option>
                                    <option value="cafetales">Cafetales</option>
                                    <option value="ayuntamiento">Ayuntamiento</option>
                                    <option value="revolucion">Revolución</option>
                                  </select>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Rfc</label>
                                <input type="text" name="rfcInvoice" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp">    
                            </div>
                            <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Nº de ticket</label>
                                <input type="number" name="ticketNum" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp">    
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Forma de pago</label>
                                <!-- <input type="text" name="rfcInvoice" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp">     -->
                                <select class="form-select" name="paymentMethod" aria-label="Forma de pago">
                                    <option value="efectivo">Efectivo</option>
                                    <option value="tarjeta">Pago con tarjeta</option>
                                  </select>
                            </div>
                            <div class="input-container">
                                <label for="branchInputInvoice" class="form-label">Monto del ticket</label>
                                <input type="number" name="ticketAmount" class="form-control" id="branchInputInvoice" aria-describedby="emailHelp" step=0.01>    
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-container">
                                <label for="phoneInputInvoice" class="form-label">Teléfono</label>
                                <input type="tel" name="phoneInvoice" class="form-control" id="phoneInputInvoice" aria-describedby="emailHelp">    
                            </div>
                            <div class="input-container">
                                <label for="emailInputInvoice" class="form-label">Email</label>
                                <input type="email" name="emailInvoice" class="form-control" id="emailInputInvoice" aria-describedby="emailHelp">    
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-container w-100">
                                <span class="form-label">¿Tienes algún comentario adicional?</span>
                                <textarea class="form-control" name="textInvoice" aria-label="With textarea"></textarea>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-container w-100">
                                <div class="mb-3">
                                    <label for="id_ticket_image" class="form-label">Selecciona foto de tu ticket</label>
                                    <input name="ticket_image" class="form-control" accept="image/*" required type="file" id="id_ticket_image">
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn send-form-event">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
    </div>
{% endblock %}

templates/landing/links.html
{% extends "base.html" %}
<!-- {% load static %} -->
{% block container %}
    <div class="wraper-link-three">
        <img class="logo-links" src="{% static 'img/logo_presentation_card.png' %}" alt="">

        <div class="container-links">
            <div class="container-link">
                <a href="{% url 'home' %}" class="link">Nuestro sitio web</a>
            </div>

            <div class="container-link">
                <a href="https://facebook.com/elperiban" class="link">Facebook</a>
            </div>
            <div class="container-link">
                <a href="https://instagram.com/elperiban" class="link">Instagram</a>
            </div>
            <div class="container-link">
                <a href="https://tiktok.com/@el_periban" class="link">Tik Tok</a>
            </div>
            <div class="container-link">
                <a href="https://wa.me/525534316660" class="link">Contácto para eventos</a>
            </div>
        </div>
    </div>
{% endblock %}  